(function () {
  "use strict";
  if (window.YaoshengAuth && !window.YaoshengAuth.requireRoles(["admin"])) return;
  if (window.YaoshengAuth) window.YaoshengAuth.mountUserArea("courses");
  const A = window.AcademicDemo, $ = (id) => document.getElementById(id);
  const els = { sidebar: $("sidebar"), menuToggle: $("menuToggle"), search: $("searchInput"), categoryFilter: $("categoryFilter"), levelFilter: $("levelFilter"), statusFilter: $("statusFilter"), table: $("tableBody"), empty: $("emptyState"), none: $("noResultState"), result: $("resultCount"), total: $("totalCount"), active: $("activeCount"), draft: $("draftCount"), archived: $("archivedCount"), seed: $("seedDemo"), newItem: $("newItem"), exportCsv: $("exportCsv"), clear: $("clearFilters"), backdrop: $("drawerBackdrop"), drawer: $("drawer"), form: $("itemForm"), itemId: $("itemId"), close: $("closeDrawer"), cancel: $("cancelDrawer"), name: $("courseName"), code: $("courseCode"), category: $("category"), level: $("level"), duration: $("duration"), capacity: $("capacity"), status: $("courseStatus"), gradeChecks: $("gradeChecks"), desc: $("description"), descCount: $("descCount"), error: $("formError"), live: $("liveMessage") };
  const grades = ["幼兒園中班", "幼兒園大班", "國小一年級", "國小二年級", "國小三年級", "國小四年級", "國小五年級", "國小六年級"];
  let filtered = [], lastFocus = null;
  function trackCourseEvent(eventName, eventData = {}) { console.log("[Course Demo Tracking]", eventName, eventData); }
  function label(map, value) { return A.labels[map][value] || value || "未填寫"; }
  function html(value) { return String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function date(value) { return value ? new Intl.DateTimeFormat("zh-TW", { year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)) : "未填寫"; }
  function msg(text) { els.live.textContent = text; els.live.classList.add("is-visible"); clearTimeout(msg.t); msg.t = setTimeout(() => els.live.classList.remove("is-visible"), 2400); }
  function classCount(id) { return A.loadClasses().filter((c) => c.course_id === id).length; }
  function fill() {
    const cats = Object.keys(A.labels.category), levels = Object.keys(A.labels.level), statuses = Object.keys(A.labels.course_status);
    els.categoryFilter.innerHTML = "<option value=''>全部類別</option>" + cats.map((k) => "<option value='" + k + "'>" + label("category", k) + "</option>").join("");
    els.category.innerHTML = cats.map((k) => "<option value='" + k + "'>" + label("category", k) + "</option>").join("");
    els.levelFilter.innerHTML = "<option value=''>全部級別</option>" + levels.map((k) => "<option value='" + k + "'>" + label("level", k) + "</option>").join("");
    els.level.innerHTML = levels.map((k) => "<option value='" + k + "'>" + label("level", k) + "</option>").join("");
    els.statusFilter.innerHTML = "<option value=''>全部狀態</option>" + statuses.map((k) => "<option value='" + k + "'>" + label("course_status", k) + "</option>").join("");
    els.status.innerHTML = statuses.map((k) => "<option value='" + k + "'>" + label("course_status", k) + "</option>").join("");
    els.gradeChecks.innerHTML = grades.map((g) => "<label><input type='checkbox' value='" + g + "'> " + g + "</label>").join("");
  }
  function selectedGrades() { return Array.from(els.gradeChecks.querySelectorAll("input:checked")).map((i) => i.value); }
  function setGrades(values) { Array.from(els.gradeChecks.querySelectorAll("input")).forEach((i) => { i.checked = (values || []).indexOf(i.value) >= 0; }); }
  function render() {
    const q = els.search.value.trim().toLowerCase(), cat = els.categoryFilter.value, lv = els.levelFilter.value, st = els.statusFilter.value, courses = A.loadCourses();
    filtered = courses.filter((c) => { const hay = [c.id, c.course_name, c.course_code].join(" ").toLowerCase(); return (!q || hay.indexOf(q) >= 0) && (!cat || c.category === cat) && (!lv || c.level === lv) && (!st || c.course_status === st); });
    els.total.textContent = courses.length; els.active.textContent = courses.filter((c) => c.course_status === "active").length; els.draft.textContent = courses.filter((c) => c.course_status === "draft").length; els.archived.textContent = courses.filter((c) => c.course_status === "archived").length;
    els.result.textContent = "目前顯示 " + filtered.length + " 筆，共 " + courses.length + " 筆"; els.empty.hidden = courses.length !== 0; els.none.hidden = courses.length === 0 || filtered.length !== 0; els.table.innerHTML = "";
    filtered.forEach((c) => { const tr = document.createElement("tr"); tr.innerHTML = "<td><strong>" + html(c.id) + "</strong></td><td>" + html(c.course_name) + "</td><td>" + html(c.course_code || "未填寫") + "</td><td>" + label("category", c.category) + "</td><td>" + label("level", c.level) + "</td><td>" + html((c.suitable_grades || []).join("、") || "未填寫") + "</td><td>" + html(c.default_capacity || 0) + "</td><td>" + classCount(c.id) + "</td><td><span class='status-badge status-" + (c.course_status === "active" ? "enrolled" : "pending_contact") + "'>" + label("course_status", c.course_status) + "</span></td><td><div class='row-actions'><button data-action='view' data-id='" + c.id + "'>查看詳情</button><button class='danger' data-action='delete' data-id='" + c.id + "'>刪除</button></div></td>"; els.table.appendChild(tr); });
  }
  function open(id, trigger) { const c = id ? A.getCourseById(id) : null; lastFocus = trigger || document.activeElement; els.itemId.value = id || ""; els.name.value = c ? c.course_name || "" : ""; els.code.value = c ? c.course_code || "" : ""; els.category.value = c ? c.category || "comprehensive" : "comprehensive"; els.level.value = c ? c.level || "beginner" : "beginner"; els.duration.value = c ? c.lesson_duration_minutes || 90 : 90; els.capacity.value = c ? c.default_capacity || 12 : 12; els.status.value = c ? c.course_status || "active" : "active"; setGrades(c ? c.suitable_grades : []); els.desc.value = c ? c.description || "" : ""; els.descCount.textContent = els.desc.value.length; els.error.textContent = ""; els.backdrop.hidden = false; els.drawer.hidden = false; document.body.classList.add("drawer-open"); setTimeout(() => els.name.focus(), 0); }
  function close() { els.backdrop.hidden = true; els.drawer.hidden = true; document.body.classList.remove("drawer-open"); if (lastFocus) lastFocus.focus(); }
  function save(e) { e.preventDefault(); const dur = Number(els.duration.value), cap = Number(els.capacity.value); if (!els.name.value.trim()) return els.error.textContent = "請填寫課程名稱。"; if (!els.category.value || !els.level.value) return els.error.textContent = "請選擇課程類別與級別。"; if (dur < 30 || dur > 240) return els.error.textContent = "每堂時間需介於 30～240 分鐘。"; if (cap < 1 || cap > 100) return els.error.textContent = "預設容量需介於 1～100 人。"; const payload = { course_name: els.name.value.trim(), course_code: els.code.value.trim(), category: els.category.value, level: els.level.value, suitable_grades: selectedGrades(), description: els.desc.value.trim(), lesson_duration_minutes: dur, default_capacity: cap, course_status: els.status.value }; const old = els.itemId.value ? A.getCourseById(els.itemId.value) : null; if (els.itemId.value) { A.updateCourseById(els.itemId.value, payload); trackCourseEvent(old && old.course_status !== payload.course_status ? "course_status_changed" : "course_updated", { course_id: els.itemId.value }); } else { const created = A.createCourse(payload); trackCourseEvent("course_created", { course_id: created.id }); } render(); msg("課程資料已儲存"); close(); }
  function exportCsv() { const rows = filtered.map((c) => [c.id, c.course_name, c.course_code, label("category", c.category), label("level", c.level), (c.suitable_grades || []).join("、"), c.description, c.lesson_duration_minutes, c.default_capacity, label("course_status", c.course_status), c.created_at, c.updated_at].map((v) => '"' + String(v || "").replace(/"/g, '""') + '"').join(",")); const blob = new Blob(["\uFEFFid,course_name,course_code,category,level,suitable_grades,description,lesson_duration_minutes,default_capacity,course_status,created_at,updated_at\n" + rows.join("\n")], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"), now = new Date(); a.href = URL.createObjectURL(blob); a.download = "yaosheng-courses-" + now.getFullYear() + String(now.getMonth() + 1).padStart(2, "0") + String(now.getDate()).padStart(2, "0") + "-" + String(now.getHours()).padStart(2, "0") + String(now.getMinutes()).padStart(2, "0") + ".csv"; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(a.href); }
  fill(); render(); [els.search, els.categoryFilter, els.levelFilter, els.statusFilter].forEach((i) => { i.addEventListener("input", render); i.addEventListener("change", render); }); els.clear.addEventListener("click", () => { els.search.value = ""; els.categoryFilter.value = ""; els.levelFilter.value = ""; els.statusFilter.value = ""; render(); }); els.newItem.addEventListener("click", (e) => open("", e.target)); els.exportCsv.addEventListener("click", exportCsv); els.seed.addEventListener("click", () => { msg(A.seedDemoData() ? "Demo 範例資料已建立" : "Demo 範例資料已存在"); render(); }); els.table.addEventListener("click", (e) => { const id = e.target.getAttribute("data-id"); if (e.target.getAttribute("data-action") === "view") open(id, e.target); if (e.target.getAttribute("data-action") === "delete") { if (!window.confirm("確定要刪除這個 Demo 課程？")) return; if (!A.deleteCourseById(id)) return msg("此課程已有開設班級，請改為封存或先移除相關班級。"); trackCourseEvent("course_deleted", { course_id: id }); render(); msg("課程已刪除"); } }); els.form.addEventListener("submit", save); els.close.addEventListener("click", close); els.cancel.addEventListener("click", close); els.backdrop.addEventListener("click", close); els.desc.addEventListener("input", () => els.descCount.textContent = els.desc.value.length); els.menuToggle.addEventListener("click", () => { const openMenu = els.sidebar.classList.toggle("is-open"); els.menuToggle.setAttribute("aria-expanded", String(openMenu)); }); document.querySelectorAll("[data-coming-soon]").forEach((b) => b.addEventListener("click", () => msg("此功能將於下一階段建立。"))); document.addEventListener("keydown", (e) => { if (e.key === "Escape" && !els.drawer.hidden) close(); });
})();
